---
title: Promise
published: 2025-03-14
description: I promise you!
tags: [JS, Async JS]
category: Async JS
licenseName: "Unlicensed"
author: aigle
---

## Promise

**Promise** is a guarantee that an action *will* happen in the near future. If that action doesn't happen, the program will be notified.

Eg : I can promise that I'll give you a present this Christmas. Suppose, I can't do so, I'll let you know beforehand.

```js
let promise = new Promise(
    function(resolve, reject){
        //do something
    }
);
```

### Types

A Promise has 2 parts.

- **Producing code** : It produces something and this takes time.
- **Consuming code** : It wants the result of the producing code.

## How does it work?

A function called **executor** is passed as a callback to `Promise()`. It contains the producing part.

It has 2 arguments - `resolve` and `reject`. The executor calls one of these callbacks when it returns a value.

- `resolve(value)` : Job is done successfully.
- `reject(error)` : Error has occurred.

A promise can either be resolved or rejected.

Here, the promise gets resolved after 3 sec.

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("true"), 3000);
});
```

However, we can't just call `reject()` like we do with `resolve()`. We've to create an `Error` object inside it.

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => reject("true"), 3000);
});
/*
[UnhandledPromiseRejection: This error
originated ...]
*/
```

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error('no')), 3000);
});
```

> An executor may have only one `resolve` or `reject`. Any change in state is final and can't be changed further.

## Properties of the `promise` object

`state` is the state of the object. It starts as `pending` and changes to `fulfilled` when resolved and `rejected` when rejected.

`result` is the return value obtained by executor. It is initially `undefined`, then changes to `value` when `resolve(value)` is called or `error` when `reject(error)` is called.

Although the promise will be resolved in 3 sec., ``console.log()`` will be printed first.

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("true"), 3000);
});

console.log(promise); //Promise { <pending> }
```

In this case, promise has been resolved. ``console.log()`` will now return `resolve()`'s argument.

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("true"), 3000);
});

setTimeout(() => console.log(promise), 4000); //Promise { 'true' }
```

In case of `reject()`, an error is returned.

```js
let promise = new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error('no')), 3000);
});

setTimeout(() => console.log(promise), 4000);
/*
setTimeout(() => reject(new Error('no')), 3000);
                            ^
Error: no
*/
```
